# Generated by Django 3.1 on 2020-08-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('search_keyword', models.CharField(max_length=100)),
                ('search_time', models.DateField(auto_now_add=True)),
                ('search_engine_name', models.CharField(max_length=50)),
                ('search_keyword_language', models.CharField(max_length=50)),
            ],
        ),
    ]
