# Generated by Django 3.1 on 2020-08-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_time',
            field=models.DateField(),
        ),
    ]
